---
title: "Udemy Data Project"
format: html
---

# Project

This is a easy shor project about how to use R when you're a beginer in the language.

The dataset is a "public" dataset about top 1000 movie qualification on the website IMDB

## Data import and Transformation

```{r}
# Required Libraries

library(ggplot2)
library(dplyr)
library(readr)

# Import data
imbd_data <- read_csv("./R-FirstSteps/udemy_course/data/imdb_top_1000.csv")

# Omit null values
imbd_data <- na.omit(imbd_data)

# transform data
imbd_data$Released_Year <- as.numeric(imbd_data$Released_Year)
imbd_data$IMDB_Rating <- as.numeric(imbd_data$IMDB_Rating)
imbd_data$Main_Genre <- sapply(strsplit(imbd_data$Genre, ","), `[`, 1)

# Review summarise data
summary(imbd_data)
```

Once the data is ready is possible to continue

# Data Analysis

Here we'll review and analyze the qualification and trends

## Qualification Histogram

```{r}
library(ggplot2)
ggplot(imbd_data, aes(x = IMDB_Rating)) +
  geom_histogram(binwidth = 0.5, fill = "red", color = "gray", alpha = 0.7) +
  labs(title = "Qualification Distribution IMBD", x = "Qualification", y = "Frequency") +
  theme_minimal()
```